apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasetmaker   # Deployment name
  namespace: kafka     # Namespace where the deployment will be created
spec:
  selector:
    matchLabels:
      app: datasetmaker  # Select the pods with the label "app: datasetmaker"
  replicas: 1           # Number of replicas to create
  template:
    metadata:
      labels:
        app: datasetmaker  # Label for the pod(s) created by this deployment
    spec:
      containers:
      - name: datasetmaker   # Name of the container
        image: mikaelsabuhi/dataset_maker:latest   # Docker image for the container
        env:
        - name: ELASTIC_PASSWORD   # Environment variable
          value: "elasticpassword"  # Value for the environment variable
        resources:
          requests:
            memory: "2G"    # Memory requested for the container
            cpu: "0.25"      # CPU requested for the container
          limits:
            memory: "2G"    # Memory limit for the container
            cpu: "0.25"      # CPU limit for the container
