apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 5
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-1
        image: mikaelsabuhi/user_generator:latest
        env:
        - name: IP_CONF
          value: "35.239.31.74"
        - name: IP_WEB
          value: "34.172.236.32"
        - name: DATASET_NAME
          value: "MNIST"
        resources:
          requests:
            memory: "6G"
            cpu: "1"
          limits:
            memory: "10G"
            cpu: "1"
      - name: users-2
        image: mikaelsabuhi/user_generator:latest
        env:
        - name: IP_CONF
          value: "35.239.31.74"
        - name: IP_WEB
          value: "34.172.236.32"
        - name: DATASET_NAME
          value: "MNIST"
        resources:
          requests:
            memory: "6G"
            cpu: "1"
          limits:
            memory: "10G"
            cpu: "1"