apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 10
  template:
    metadata:
      labels:
        app: users
    spec:

      containers:

      - name: users-1
        image: mikaelsabuhi/user_generator
        env:
        - name: IP_CONF
          value: "34.27.71.249"
        - name: IP_WEB
          value: "34.134.73.171"
        - name: DATASET_NAME
          value: "CIFAR-10"
        resources:
          requests:
            memory: "15G"
            cpu: "2.5"
          limits:
            memory: "20G"
            cpu: "2.5"

      - name: users-2
        image: mikaelsabuhi/user_generator
        env:
        - name: IP_CONF
          value: "34.27.71.249"
        - name: IP_WEB
          value: "34.134.73.171"
        - name: DATASET_NAME
          value: "CIFAR-10"
        resources:
          requests:
            memory: "15G"
            cpu: "2.5"
          limits:
            memory: "20G"
            cpu: "2.5"

      - name: users-3
        image: mikaelsabuhi/user_generator
        env:
        - name: IP_CONF
          value: "34.27.71.249"
        - name: IP_WEB
          value: "34.134.73.171"
        - name: DATASET_NAME
          value: "CIFAR-10"
        resources:
          requests:
            memory: "15G"
            cpu: "2.5"
          limits:
            memory: "20G"
            cpu: "2.5"

      - name: users-4
        image: mikaelsabuhi/user_generator
        env:
        - name: IP_CONF
          value: "34.27.71.249"
        - name: IP_WEB
          value: "34.134.73.171"
        - name: DATASET_NAME
          value: "CIFAR-10"
        resources:
          requests:
            memory: "15G"
            cpu: "2.5"
          limits:
            memory: "20G"
            cpu: "2.5"

      - name: users-5
        image: mikaelsabuhi/user_generator
        env:
        - name: IP_CONF
          value: "34.27.71.249"
        - name: IP_WEB
          value: "34.134.73.171"
        - name: DATASET_NAME
          value: "CIFAR-10"
        resources:
          requests:
            memory: "15G"
            cpu: "2.5"
          limits:
            memory: "20G"
            cpu: "2.5"