apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: kafka
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  selector: 
    # matchLabels:
    app: web
  type: LoadBalancer    